name: React Build Action

run-name: Building a react app

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: npm test

      - name: Xanitizer Security Analysis
        uses: RIGS-IT/xanitizer-action@v1
        with:
        license: ${{ secrets.XANITIZER_LICENSE }}